{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sensorreader.serviceAccountName" . }}
  labels:
{{ include "sensorreader.labels" . | indent 4 }}
{{- end -}}
